### ISSUE TITLE
BillsList 페이지 넘길 때 조회수 0인 발의안 업데이트 안되는 문제 발생

### ISSUE THREAD

**Issue by young-st511** [oxopolitics-internship-for-zerobase/LawsCloud#75]
BillsList 페이지 넘길 때 조회수가 0인 경우 조회수가 업데이트 되지 않습니다

**Comment by mandarin-sep** [comment]
조회수가 없는 발의안은 FireStore 문서가 없어서 업데이트가 되지 않았음
문서가 없는 발의안은 viewCount를 0으로 줘서 해결
